### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by mathstuf** [mozilla/fxa-auth-db-server#159]
It appears that this has been merged into mozilla/fxa-auth-db-mysql? There are changes there which haven't made their way to this repo. Is that the way this is supposed to be used now? What about folks wanting alternate backends? Do they also bundle?

**Comment by shane-tomlinson** [comment]
@rfk to take action.

**Comment by rfk** [comment]
Hi @mathstuf, yes, that's broadly accurate, it was proving to be too much overhead to manage separate auth-db-server, auth-db-mem and auth-db-mysql repos, so they all wound up merged into auth-db-mysql.

IIRC the plan was that we'd publish the fxa-auth-db-server subdirectory from there  [1] as a stand-alone package on npm, so that users who want to write an alternate backend can pull it in without all the mem/mysql stuff.  Does that sound acceptable for your use-case?  If so I'll see about getting it done.

[1] https://github.com/mozilla/fxa-auth-db-mysql/tree/master/fxa-auth-db-server

**Comment by rfk** [comment]
I also added a short note to the above effect in the README.

**Comment by rfk** [comment]
Published here: https://www.npmjs.com/package/fxa-auth-db-server

**Comment by mathstuf** [comment]
Thanks! It will probably be enough (though I'm a complete newcomer to this npm stuff). I'm going to try my hand at a pgsql backend, but no idea how well it will go :) .
