### ISSUE TITLE
Create a new API and stored procedure to do password verification inside the DB

### ISSUE THREAD

**Issue by fmarier** [mozilla/fxa-auth-db-server#88]
As part of https://github.com/mozilla/fxa-auth-server/issues/807, a new API for password verification will be needed:

    api.post('/account/:id/checkPassword', reply(db.checkPassword))

Initially, that API call can simply grab the password hash from the user table and compare it with the hash given as a parameter.

The ultimate goal should be to create a stored procedure that will receive the password hash from the auth server and then compare it with the hash inside the DB without ever leaking that hash to the auth-server or the auth-db-server.

**Comment by eoger** [comment]
Okay the project moved a lot since I did these pull requests (db-mysql repo was created etc).
I canceled the rotting pull requests and I recreated updated new ones.
Let me know what you think guys.

**Comment by chilts** [comment]
Hi @eoger - all I can say is that this is fantastic! :) Thanks for these PRs. Everything I've looked at seems fine with just a few minor clarifications or nitpicks. The nits are all mine!

I won't merge anything until we're r+'d with all the repos and at that point I'd probably look through it all again with more of an eye across all the repos together. Cheers.

**Comment by chilts** [comment]
This can finally be closed, thanks to @eoger.

**Comment by eoger** [comment]
:+1: Thanks to everyone!

**Comment by rfk** [comment]
Thanks @eoger and @chilts!

> an as-yet-unfiled follow-up bug that removes verifyHash from the email record row

I don't recall if we ever filed this as a proper bug or not.  Basically we need to modify the SP behind `db.emailRecord` and friends so that we don't ever `SELECT` the verifier hash out of the db at all.  This completes the security story of "the webheads never see the verifier hash at all".

@eoger can you please confirm whether this was covered in your existing suite of PRs, or if we should file a follow-up bug against fxa-auth-db-mysql?  (FWIW, I don't think we can deploy such a change until after this lot goes into production, as it would ruin backwards-compat with the previous train).

**Comment by chilts** [comment]
The first part (the main part really) of this is done. Just the removal of the verifyHash from the db-server responses, since the auth-server no longer needs it.

**Comment by eoger** [comment]
PRs are ready ;)

**Comment by chilts** [comment]
Yep, thanks @eoger, we'll be putting them in the next train, or perhaps the one after. train-41 or later. :)
